Update auto-merge.yml

diff --git a/.github/workflows/auto-merge.yml b/.github/workflows/auto-merge.yml
--- a/.github/workflows/auto-merge.yml
+++ b/.github/workflows/auto-merge.yml
@@ -35,7 +35,15 @@ jobs:
           PR_BRANCH: ${{ github.head_ref }}
         run: |
           git merge --no-ff origin/$PR_BRANCH || true  # Если конфликты, решаем вручную
-
+          
+      - name: Debug PAT_TOKEN
+        run: |
+          if [[ -z "${{ secrets.PAT_TOKEN }}" ]]; then
+            echo "PAT_TOKEN is missing!"
+            exit 1
+          else
+            echo "PAT_TOKEN is set!"
+          fi
       - name: Push merged changes
         env:
           PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
